engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: false
languages:
  Ruby: true
  Javascript: true
exclude_paths:
- coverage/**/*
- public/**/*
- db/**/*
- app/assets/**/*
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
